In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
new_df = df.copy()

new_df = new_df.dropna(subset='salary_year_avg')

new_df.head(5)

    job_title_short  ...                                    job_type_skills
28   Data Scientist  ...  {'analyst_tools': ['excel'], 'libraries': ['gd...
77    Data Engineer  ...  {'analyst_tools': ['tableau'], 'cloud': ['orac...
92    Data Engineer  ...                 {'programming': ['sql', 'python']}
100  Data Scientist  ...  {'programming': ['sql', 'r', 'python'], 'webfr...
109    Data Analyst  ...  {'analyst_tools': ['alteryx', 'tableau'], 'pro...

[5 rows x 17 columns]

In [4]:
frac_df = df.sample(frac=0.1)

frac_df.head(5)

         job_title_short  ...                                    job_type_skills
707400     Data Engineer  ...  {'analyst_tools': ['ssis', 'power bi', 'tablea...
126321      Data Analyst  ...  {'analyst_tools': ['excel', 'tableau'], 'progr...
702399  Business Analyst  ...  {'analyst_tools': ['excel', 'powerpoint', 'tab...
755808     Data Engineer  ...  {'cloud': ['oracle', 'aws', 'azure'], 'databas...
196381      Data Analyst  ...  {'analyst_tools': ['sheets', 'tableau'], 'asyn...

[5 rows x 17 columns]

In [5]:
cleaned_df = df.copy()

median_salary = cleaned_df['salary_year_avg'].median()
cleaned_df['salary_year_avg'] = cleaned_df['salary_year_avg'].fillna(median_salary)

cleaned_df.head(5)

        job_title_short  ...                                    job_type_skills
0  Senior Data Engineer  ...                                                NaN
1          Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
2         Data Engineer  ...  {'analyst_tools': ['dax'], 'cloud': ['azure'],...
3         Data Engineer  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
4         Data Engineer  ...  {'cloud': ['oracle', 'aws'], 'other': ['ansibl...

[5 rows x 17 columns]