In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [5]:
df.pivot_table(index=['job_title_short', 'job_country'],aggfunc='size').head(10)

job_title_short   job_country
Business Analyst  Afghanistan      4
                  Albania         11
                  Algeria         21
                  Angola           1
                  Argentina      453
                  Armenia         29
                  Australia      928
                  Austria        738
                  Azerbaijan      16
                  Bahamas          5
dtype: int64

In [6]:
df.pivot_table(values='salary_year_avg', index='company_name', aggfunc=['max','min','mean']).head(5)

                                    max             min            mean
                        salary_year_avg salary_year_avg salary_year_avg
company_name
#twiceasnice Recruiting   120000.000000    61000.000000    77750.000000
/dev/color                125000.000000   125000.000000   125000.000000
0nward Select              92500.000000    92500.000000    92500.000000
1 Point System            137290.484375   137290.484375   137290.484375
1 Point System LLC.       170000.000000   170000.000000   170000.000000

In [10]:
new_df = df[
    (df['job_title_short'] == 'Data Scientist') &
    (df['salary_year_avg'] > 200000)
]
new_df

       job_title_short  ...                                    job_type_skills
100     Data Scientist  ...  {'programming': ['sql', 'r', 'python'], 'webfr...
2346    Data Scientist  ...                 {'programming': ['sql', 'python']}
3593    Data Scientist  ...                                                NaN
4332    Data Scientist  ...  {'analyst_tools': ['excel'], 'cloud': ['bigque...
5628    Data Scientist  ...            {'programming': ['r', 'python', 'sql']}
...                ...  ...                                                ...
779368  Data Scientist  ...                                                NaN
781090  Data Scientist  ...                 {'programming': ['python', 'sql']}
785290  Data Scientist  ...                                                NaN
785324  Data Scientist  ...  {'analyst_tools': ['tableau'], 'databases': ['...
785648  Data Scientist  ...  {'cloud': ['azure', 'snowflake'], 'libraries':...

[532 rows x 17 columns]

In [11]:
new_df.pivot_table(values='salary_year_avg', index=['company_name','job_country']).head(10)

                                 salary_year_avg
company_name      job_country
84.51             United States         225000.0
84.51°            United States         221875.0
ACT               Sudan                 225000.0
                  United States         225000.0
ANSER Corporation United States         225000.0
AT&T              Sudan                 212000.0
                  United States         214379.5
Abbott            United States         204000.0
Airbnb            United States         213750.0
Airtable          Sudan                 215500.0